#!/bin/bash
clear
#--------[ COPIADO POR @gatesccn ]-----------#
source ShellBot.sh
touch lista
[[ -z $1 ]] && {
    clear && echo "INFORME DE TOKEN" && return 0
}
# Informações Server 2
ip_server2="-IP-AQUI"
senha_server2="-Contra-AQUI"
# Informações Server 3
ip_server3="-IP-AQUI"
senha_server3="-Contra-AQUI"
[[ ! -e RESET ]] && touch RESET
api_bot=$1
ShellBot.init --token "$api_bot" --monitor --flush
ShellBot.username

# - Funcao menu
menu() {
    local msg
        msg="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="✌️😃 Hola <b>${message_from_first_name[$id]}</b>, Bienvenido!\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="<b>Genere Su Usuario Gratis x6 Horas</b>\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="<b>Funcionable para Cualquier pais que use cloudflare</b>\n"
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - Funcao pix no esta en uso creo actualmente buscar (19 mayo)
PIX() {
    local msg
        msg="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="💠 BUENAS Y BIENVENIDO 💠\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="👿 PARA OBTENER UN SERVICIO PAGADO PIX GRANDE👿\n"
        msg+="📞 ├ WHATSAPP +59162069439\n"
        msg+="📞 ├ WHATSAPP +59169008438"
        msg+="👤 ├ El Mandarin Sniff"
        msg+="├CLASES DESDE"
        msg+="💰 └ Cops$ 20,00\n"
        msg+="5USD"
        msg+="├VPS DESDE"
        msg+="💰 └ Cops$ 20,00\n"
        msg+="5USD"
        msg+="├Y MUCHA MAS VARIEDAD DE APLIACIONES Y COSAS SOBRE NETFREE"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="✅       ENVIAR EL PAGO Y        ✅\n"
        msg+="ENVIAR PRUEBA A @gatesccn\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="VERIFICACIÓN DE PAGO EN 6 HORAS MAXIMO\n"
        msg+="ACEPTAMOS\n"
        msg+="-NEQUI   -BANCO COLOMBIA\n"
        msg+="-PAYPAL  -AIRTM GIFTCARD\n"
        msg+="-TIGO MONEY -BANCO UNION\n"
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - Funcao pix
pix() {
    local msg
        msg="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="💠 BUENAS Y BIENVENIDO 💠\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="👿 PARA OBTENER UN SERVICIO PAGADO 👿\n"
        msg+="📞 ├ WHATSAPP +59162069439\n"
        msg+="📞 ├ WHATSAPP +59169008438"
        msg+="👤 ├ El Mandarin Sniff"
        msg+="├CLASES DESDE"
        msg+="💰 └ Cops$ 20,00\n"
        msg+="5USD"
        msg+="├VPS DESDE"
        msg+="💰 └ Cops$ 20,00\n"
        msg+="5USD"
        msg+="├Y MUCHA MAS VARIEDAD DE APLIACIONES Y COSAS SOBRE NETFREE"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="✅       ENVIAR EL PAGO Y        ✅\n"
        msg+="ENVIAR PRUEBA A @gatesccn\n"
        msg+="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n"
        msg+="VERIFICACIÓN DE PAGO EN 6 HORAS MAXIMO\n"
        msg+="ACEPTAMOS\n"
        msg+="-NEQUI   -BANCO COLOMBIA\n"
        msg+="-PAYPAL  -AIRTM GIFTCARD\n"
        msg+="-TIGO MONEY -BANCO UNION\n"
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - funcao criar ssh
criarteste() {
    [[ $(grep -wc ${callback_query_from_id} lista) != '0' ]] && {
      ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "❌ Acceso denegado, INTENTE EN 24 HORAS O COMPRE UN ACCESO VIP."
      return 0
    }
    usuario=$(echo MANDARIN$(( RANDOM% + 999 )))
    senha=$(echo GRATIS$(( RANDOM% + 999 )))
    limite='1'
    tempo='6'
    tuserdate=$(date '+%C%y/%m/%d' -d " +1 days")
    useradd -M -N -s /bin/false $usuario -e $tuserdate > /dev/null 2>&1
    (echo "$senha";echo "$senha") | passwd $usuario > /dev/null 2>&1
    echo "$senha" > /etc/SSHPlus/senha/$usuario
    echo "$usuario $limite" >> /root/usuarios.db
    echo "#!/bin/bash
pkill -f "$usuario"
userdel --force $usuario
grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/SSHPlus/senha/$usuario > /dev/null 2>&1
rm -rf /etc/SSHPlus/userteste/$usuario.sh" > /etc/SSHPlus/userteste/$usuario.sh
    chmod +x /etc/SSHPlus/userteste/$usuario.sh
    at -f /etc/SSHPlus/userteste/$usuario.sh now + $tempo hour > /dev/null 2>&1
    echo ${callback_query_from_id} >> lista
    # - ENVIA O SSH
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
    --text "$(echo -e "▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n        ✅ Creado Con Exito ✅\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n            👤 USUARIO: <code>$usuario</code>\n               🔑 CONTRASEÑA: <code>$senha</code>\n             ⏰ Expira en: $tempo Hora")\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n   ℹ️ COMO CONECTAR A INTERNET\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n• Abra la aplicación que instalaste.\n• Selecione su operadora.\n• Digite o usuário y a Contra recebida en su app.\n• Activa los datos móviles y desactiva Wi-Fi\n• Haz clic en Conectar.\n• Debe aparecer Conexión establecida.\n• Si apareció, mira youtube y compruébalo.\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n ⚠️ SIGUE EXACTAMENTE COMO DICE\n▬▬▬▬▬▬▬▬▬ ▬▬ ▬ ▬ ▬▬▬▬▬▬\n 😍 TE GUSTA? ESCRIBE EL HAGA CLIC EN /PIX" \
    --parse_mode html
    return 0
}

# - funcao criar ssh 2
criarteste2() {
   [[ $(grep -wc ${callback_query_from_id} lista) != '0' ]] && {
      ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "❌ Acceso denegado, verifique la hora de su última creación y regrese solo cuando complete 24 horas de su última creación. !"
      return 0
    }
    usuario=$(echo teste$(( RANDOM% + 250 )))
    senha=$((RANDOM% + 99999))
    limite='1'
    tempo='1'
    tuserdate=$(date '+%C%y/%m/%d' -d " +1 days")
    if sshpass -p "$senha_server2" ssh -o ConnectTimeout=2 -o StrictHostKeyChecking=no root@$ip_server2 echo "ok" 1>/dev/null 2>/dev/null; then
		sshpass -p "$senha_server2" ssh -o ConnectTimeout=2 -o StrictHostKeyChecking=no root@$ip_server2 << EOF
		useradd -M -N -s /bin/false $usuario -e $tuserdate > /dev/null 2>&1
    (echo "$senha";echo "$senha") | passwd $usuario > /dev/null 2>&1
    echo "$senha" > /etc/SSHPlus/senha/$usuario
    echo "$usuario $limite" >> /root/usuarios.db
    echo "#!/bin/bash
pkill -f "$usuario"
userdel --force $usuario
grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/SSHPlus/senha/$usuario > /dev/null 2>&1
rm -rf /etc/SSHPlus/userteste/$usuario.sh" > /etc/SSHPlus/userteste/$usuario.sh
chmod +x /etc/SSHPlus/userteste/$usuario.sh
at -f /etc/SSHPlus/userteste/$usuario.sh now + $tempo hour > /dev/null 2>&1
EOF
	echo ${callback_query_from_id} >> lista
    # - ENVIA O SSH
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
    --text "$(echo -e "✅ <b>Creado con exito </b> ✅\n\nIP: $ip_server2\nUSUARIO: <code>$usuario</code>\nContraseña: <code>$senha</code>\n\n⏳ Expira en: $tempo Hora")" \
    --parse_mode html
    return 0
else
ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
	--text "$(echo -e Erro Tente novamente Mais tarde!)" \
	--parse_mode html
	return 0
fi
}

# - funcao criar ssh 3
criarteste3() {
	[[ $(grep -wc ${callback_query_from_id} lista) != '0' ]] && {
      ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "❌ Acceso denegado, verifique la hora de su última creación y regrese solo cuando complete 24 horas de su última creación.. !"
      return 0
    }
    usuario=$(echo teste$(( RANDOM% + 250 )))
    senha=$((RANDOM% + 99999))
    limite='1'
    tempo='1'
    tuserdate=$(date '+%C%y/%m/%d' -d " +1 days")
    if sshpass -p "$senha_server3" ssh -o ConnectTimeout=2 -o StrictHostKeyChecking=no root@$ip_server3 echo "ok" 1>/dev/null 2>/dev/null; then
		sshpass -p "$senha_server3" ssh -o ConnectTimeout=2 -o StrictHostKeyChecking=no root@$ip_server3 << EOF
		useradd -M -N -s /bin/false $usuario -e $tuserdate > /dev/null 2>&1
    (echo "$senha";echo "$senha") | passwd $usuario > /dev/null 2>&1
    echo "$senha" > /etc/SSHPlus/senha/$usuario
    echo "$usuario $limite" >> /root/usuarios.db
    echo "#!/bin/bash
pkill -f "$usuario"
userdel --force $usuario
grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/SSHPlus/senha/$usuario > /dev/null 2>&1
rm -rf /etc/SSHPlus/userteste/$usuario.sh" > /etc/SSHPlus/userteste/$usuario.sh
chmod +x /etc/SSHPlus/userteste/$usuario.sh
at -f /etc/SSHPlus/userteste/$usuario.sh now + $tempo hour > /dev/null 2>&1
EOF
	echo ${callback_query_from_id} >> lista
    # - ENVIA O SSH
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
    --text "$(echo -e "✅ <b>Creado Con Exito</b> ✅\n\nIP: $ip_server3\nUSUARIO: <code>$usuario</code>\nContraseña: <code>$senha</code>\n\n⏳ Expira en: $tempo Hora")" \
    --parse_mode html
    return 0
else
ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
	--text "$(echo -e Erro Tente novamente Mais tarde!)" \
	--parse_mode html
	return 0
fi
}

#informacoes usuario
infouser () {
	ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
	--text "$(echo -e "Nombre:  ${message_from_first_name[$(ShellBot.ListUpdates)]}\nUsuario: @${message_from_username[$(ShellBot.ListUpdates)]:-null}")\nID: ${message_from_id[$(ShellBot.ListUpdates)]} " \
	--parse_mode html
	return 0
}

unset botao1
botao1=''
ShellBot.InlineKeyboardButton --button 'botao1' --line 1 --text '📡 SSH GRATIS X6 HORAS 👿' --callback_data 'gerarssh'
ShellBot.InlineKeyboardButton --button 'botao1' --line 2 --text '📥 Aplicacion MediaFire 📥' --callback_data '2' --url 'https://github.com/Gatesccn/APKSGRATIS/raw/main/base.apk' # LINK APP
ShellBot.InlineKeyboardButton --button 'botao1' --line 3 --text '👽 ENTRA A NUESTRO GRUPO PRIVADO 👽' --callback_data '2' --url 'https://t.me/+ucJjL1ZDuRsyNmRh' # LINK PV
ShellBot.InlineKeyboardButton --button 'botao1' --line 3 --text '👽 ENTRA A NUESTRO GRUPO PRIVADO 2 👽' --callback_data '2' --url 'https://t.me/+ucJjL1ZDuRsyNmRh' # LINK PV
ShellBot.InlineKeyboardButton --button 'botao1' --line 4 --text '🔐 HABLA CON EL ADMIN🍊' --callback_data '2' --url 't.me/gatesccn' # LINK PV
ShellBot.regHandleFunction --function criarteste --callback_data gerarssh
ShellBot.regHandleFunction --function criarteste2 --callback_data gerarssh2
ShellBot.regHandleFunction --function criarteste3 --callback_data gerarssh3
unset keyboard1
keyboard1="$(ShellBot.InlineKeyboardMarkup -b 'botao1')"
while :; do
   [[ "$(date +%d)" != "$(cat RESET)" ]] && {
   	echo $(date +%d) > RESET
   	echo ' ' > lista
   }
  ShellBot.getUpdates --limit 100 --offset $(ShellBot.OffsetNext) --timeout 30
  for id in $(ShellBot.ListUpdates); do
    (
      ShellBot.watchHandle --callback_data ${callback_query_data[$id]}
      comando=(${message_text[$id]})
      [[ "${comando[0]}" = "/menu"  || "${comando[0]}" = "/start" ]] && menu
      [[ "${comando[0]}" = "/PIX"  ]] && pix
    ) &
  done
done
